let a = 100;
let b = 500;
let c = "hello";
let d = "okten";
let x = 'constant value';
console.log(a);
console.log(b, c, d, x);
x = 'new value';
b = 'new value';
console.log(x, b);
let result = 100 + a;
console.log(result);